# Generated by Django 3.1.4 on 2020-12-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pizzashopmodel',
            table='pizza_shop',
        ),
    ]
