# Generated by Django 3.1.4 on 2020-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20201217_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назвавине')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('cost', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Пицу',
                'verbose_name_plural': 'Пицы',
                'db_table': 'pizza',
            },
        ),
        migrations.AlterModelOptions(
            name='pizzashopmodel',
            options={'verbose_name': 'Пицерию', 'verbose_name_plural': 'Пицерии'},
        ),
        migrations.AlterField(
            model_name='pizzashopmodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pizzashopmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pizzashopmodel',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рэйтинг'),
        ),
    ]
