# Generated by Django 3.1.4 on 2020-12-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20201217_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='pizza_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzashopmodel'),
            preserve_default=False,
        ),
    ]
