# Generated by Django 3.1.4 on 2020-12-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_pizzamodel_pizza_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('name',), 'verbose_name': 'Пицу', 'verbose_name_plural': 'Пицы'},
        ),
        migrations.AlterModelOptions(
            name='pizzashopmodel',
            options={'ordering': ('name',), 'verbose_name': 'Пицерию', 'verbose_name_plural': 'Пицерии'},
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='pizza_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizza.pizzashopmodel'),
        ),
    ]
