# Generated by Django 3.1.4 on 2020-12-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20201222_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='pizza/photos', verbose_name='Фото'),
        ),
    ]
