# Generated by Django 3.1.4 on 2020-12-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashopmodel',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Название'),
        ),
    ]
